// <auto-generated />
using CoffeeVendingMachineAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeVendingMachineAPI.Migrations
{
    [DbContext(typeof(CoffeeContext))]
    [Migration("20250521183454_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoffeeCustomizationCoffeeOrder", b =>
                {
                    b.Property<int>("CoffeeOrderId")
                        .HasColumnType("int");

                    b.Property<int>("CustomizationsId")
                        .HasColumnType("int");

                    b.HasKey("CoffeeOrderId", "CustomizationsId");

                    b.HasIndex("CustomizationsId");

                    b.ToTable("OrderCustomizations", (string)null);
                });

            modelBuilder.Entity("CoffeeVendingMachineAPI.Models.CoffeeCustomization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customizations");
                });

            modelBuilder.Entity("CoffeeVendingMachineAPI.Models.CoffeeOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CoffeeTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeTypeId");

                    b.ToTable("CoffeeOrders");
                });

            modelBuilder.Entity("CoffeeVendingMachineAPI.Models.CoffeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CoffeeTypes");
                });

            modelBuilder.Entity("CoffeeCustomizationCoffeeOrder", b =>
                {
                    b.HasOne("CoffeeVendingMachineAPI.Models.CoffeeOrder", null)
                        .WithMany()
                        .HasForeignKey("CoffeeOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeVendingMachineAPI.Models.CoffeeCustomization", null)
                        .WithMany()
                        .HasForeignKey("CustomizationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoffeeVendingMachineAPI.Models.CoffeeOrder", b =>
                {
                    b.HasOne("CoffeeVendingMachineAPI.Models.CoffeeType", "CoffeeType")
                        .WithMany()
                        .HasForeignKey("CoffeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoffeeType");
                });
#pragma warning restore 612, 618
        }
    }
}
